// Copyright (c) 2019-2026 ReactiveUI and Contributors. All rights reserved.
// ReactiveUI and Contributors licenses this file to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System;
using System.Collections.Immutable;
using System.Runtime.CompilerServices;

using Splat.DependencyInjection.SourceGenerator.Models;

namespace Splat.DependencyInjection.SourceGenerator.CodeGeneration;

/// <summary>Writes the registrations file: the body of <c>SetupIOCInternal</c>.</summary>
/// <remarks>
/// <para>
/// Every registration becomes a factory passed to Splat's generic <c>Register&lt;T&gt;</c>. A factory that needs nothing
/// from the resolver captures nothing, so the compiler caches its delegate once for the life of the application. The
/// others share the one closure the compiler creates for <c>resolver</c>.
/// </para>
/// <para>
/// A dependency the resolver does not have throws through a helper written once per file. The factory then holds a
/// call rather than the construction and concatenation of an exception, which keeps the code the factory runs on
/// every resolution small.
/// </para>
/// </remarks>
internal static class CodeGenerator
{
    /// <summary>The characters the fixed parts of the file take.</summary>
    internal const int FileCapacity = 2048;

    /// <summary>The characters a registration typically takes.</summary>
    internal const int RegistrationCapacity = 384;

    /// <summary>The name of the helpers that throw for an unregistered dependency.</summary>
    internal const string ThrowNotRegistered = "ThrowNotRegistered";

    /// <summary>The start of a registration on the resolver, before the registered type.</summary>
    private const string RegisterOpen = "resolver.Register<";

    /// <summary>The name of a lazy singleton's local, before its number.</summary>
    private const string LazyLocal = "lazy";

    /// <summary>The opening of the fully qualified <see cref="System.Lazy{T}"/> type.</summary>
    private const string LazyTypeOpen = "global::System.Lazy<";

    /// <summary>The markers at the top of the file.</summary>
    private const string FileHeader = """
        // <auto-generated/>

        #nullable enable annotations
        #nullable disable warnings

        // Suppress warnings about [Obsolete] member usage in generated code.
        #pragma warning disable CS0612, CS0618
        """;

    /// <summary>The declaration of the partial class, written inside the namespace.</summary>
    private const string ClassDeclaration = """
        /// <summary>
        /// Provides extension methods for the Splat dependency injection source generator.
        /// This partial class contains the generated implementation of dependency registrations.
        /// </summary>
        internal static partial class SplatRegistrations
        """;

    /// <summary>The declaration of the registration method, written inside the class.</summary>
    private const string MethodDeclaration = """
        /// <summary>
        /// Internal implementation of dependency injection setup.
        /// This method is generated at compile-time and contains all registrations
        /// defined through the source generator marker methods.
        /// </summary>
        /// <param name="resolver">The <see cref="Splat.IDependencyResolver"/> instance to register dependencies with.</param>
        static partial void SetupIOCInternal(Splat.IDependencyResolver resolver)
        """;

    /// <summary>The helper that throws for a dependency registered without a contract.</summary>
    private const string ThrowNotRegisteredMethod = $$"""
        /// <summary>Throws for a dependency the resolver has no registration for.</summary>
        /// <typeparam name="T">The type of the dependency.</typeparam>
        /// <param name="typeName">The name of the dependency's type.</param>
        /// <returns>Never returns.</returns>
        private static T {{ThrowNotRegistered}}<T>(string typeName)
        {
            throw new global::System.InvalidOperationException("Dependency '" + typeName + "' not registered with Splat resolver.");
        }
        """;

    /// <summary>The helper that throws for a dependency registered under a contract.</summary>
    private const string ThrowNotRegisteredWithContractMethod = $$"""
        /// <summary>Throws for a dependency the resolver has no registration for under a contract.</summary>
        /// <typeparam name="T">The type of the dependency.</typeparam>
        /// <param name="typeName">The name of the dependency's type.</param>
        /// <param name="contract">The contract the dependency was asked for under.</param>
        /// <returns>Never returns.</returns>
        private static T {{ThrowNotRegistered}}<T>(string typeName, string contract)
        {
            throw new global::System.InvalidOperationException("Dependency '" + typeName + "' with contract " + contract + " not registered with Splat resolver.");
        }
        """;

    /// <summary>Which throw helpers the written registrations call.</summary>
    [Flags]
    internal enum ThrowHelpers
    {
        /// <summary>No helper is called.</summary>
        None = 0,

        /// <summary>The helper for a dependency without a contract is called.</summary>
        WithoutContract = 1 << 0,

        /// <summary>The helper for a dependency under a contract is called.</summary>
        WithContract = 1 << 1,
    }

    /// <summary>Writes the registrations file.</summary>
    /// <param name="registrations">The registrations, in source order.</param>
    /// <returns>The source.</returns>
    /// <remarks>
    /// Transient registrations are written before lazy singletons, as they always have been. Splat resolves the last
    /// registration of a type, so the order decides which of two registrations of one type wins.
    /// </remarks>
    internal static string Generate(ImmutableArray<RegistrationInfo> registrations)
    {
        var writer = SourceWriter.Rent(FileCapacity + (registrations.Length * RegistrationCapacity))
            .Lines(FileHeader)
            .BlankLine()
            .OpenNamespace(Constants.NamespaceName)
            .Lines(ClassDeclaration)
            .OpenBlock()
            .Lines(MethodDeclaration)
            .OpenBlock();

        var used = ThrowHelpers.None;
        var written = 0;
        var lazySingletons = 0;
        foreach (var registration in registrations)
        {
            if (registration.Kind != RegistrationKind.Transient)
            {
                continue;
            }

            SeparateRegistration(writer, written);
            written++;
            AppendTransient(writer, registration, ref used);
        }

        foreach (var registration in registrations)
        {
            if (registration.Kind != RegistrationKind.LazySingleton)
            {
                continue;
            }

            SeparateRegistration(writer, written);
            written++;
            AppendLazySingleton(writer, registration, lazySingletons, ref used);
            lazySingletons++;
        }

        _ = writer.CloseBlock();
        AppendThrowHelpers(writer, used);
        return writer.CloseBlock().CloseBlock().ToStringAndReturn();
    }

    /// <summary>Writes a transient registration.</summary>
    /// <param name="writer">The writer, at the method body's level.</param>
    /// <param name="registration">The registration.</param>
    /// <param name="used">The throw helpers called so far, updated with those this registration calls.</param>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static void AppendTransient(SourceWriter writer, RegistrationInfo registration, ref ThrowHelpers used) =>
        AppendFactoryCall(
            writer.Append(RegisterOpen).Append(registration.InterfaceTypeFullName).Append(">("),
            registration,
            registration.ContractValue,
            ref used);

    /// <summary>Writes a lazy singleton registration: the lazy value, and the lazy and its value registered.</summary>
    /// <param name="writer">The writer, at the method body's level.</param>
    /// <param name="registration">The registration.</param>
    /// <param name="index">The number of lazy singletons written before this one, which names its local.</param>
    /// <param name="used">The throw helpers called so far, updated with those this registration calls.</param>
    /// <remarks>
    /// Each lazy is a local of the method itself, named by its position, rather than of a block of its own. The
    /// compiler keeps every captured local of one scope in one closure object, and <c>resolver</c> already needs one,
    /// so the lambdas that read the lazy add no closure; a block per registration would add one each.
    /// </remarks>
    internal static void AppendLazySingleton(SourceWriter writer, RegistrationInfo registration, int index, ref ThrowHelpers used)
    {
        var serviceType = registration.InterfaceTypeFullName;
        _ = writer.Append("var ").Append(LazyLocal).Append(index).Append(" = new ").Append(LazyTypeOpen).Append(serviceType).Append(">(");
        AppendFactoryCall(writer, registration, registration.LazyThreadSafetyMode, ref used);

        _ = writer.Append(RegisterOpen).Append(LazyTypeOpen).Append(serviceType).Append(">>(() => ").Append(LazyLocal).Append(index);
        _ = AppendTrailingArgument(writer, registration.ContractValue).Line(");");

        _ = writer.Append(RegisterOpen).Append(serviceType).Append(">(() => ").Append(LazyLocal).Append(index).Append(".Value");
        _ = AppendTrailingArgument(writer, registration.ContractValue).Line(");");
    }

    /// <summary>Finishes a call whose first argument is the registration's factory.</summary>
    /// <param name="writer">The writer, after the call's opening parenthesis.</param>
    /// <param name="registration">The registration.</param>
    /// <param name="lastArgument">The argument after the factory, as C# source; <see langword="null"/> for none.</param>
    /// <param name="used">The throw helpers called so far, updated with those the factory calls.</param>
    /// <remarks>
    /// A factory with nothing to resolve stays on the call's line. Otherwise each argument takes its own line, one
    /// level deeper, and the call closes after the last of them.
    /// </remarks>
    internal static void AppendFactoryCall(SourceWriter writer, RegistrationInfo registration, string? lastArgument, ref ThrowHelpers used)
    {
        if (registration.ConstructorParameters.Length == 0 && registration.PropertyInjections.Length == 0)
        {
            _ = writer.Append("() => new ").Append(registration.ConcreteTypeFullName).Append("()");
            _ = AppendTrailingArgument(writer, lastArgument).Line(");");
            return;
        }

        AppendFactory(writer.OpenContinuation(), registration, ref used);
        if (lastArgument is not null)
        {
            _ = writer.ArgumentSeparator().Append(lastArgument);
        }

        _ = writer.CloseContinuation(");");
    }

    /// <summary>Writes the lambda that constructs a registration's type, with its dependencies one per line.</summary>
    /// <param name="writer">The writer, at the start of a line.</param>
    /// <param name="registration">The registration.</param>
    /// <param name="used">The throw helpers called so far, updated with those the factory calls.</param>
    /// <remarks>Leaves the writer on the lambda's last line, for the caller to finish.</remarks>
    internal static void AppendFactory(SourceWriter writer, RegistrationInfo registration, ref ThrowHelpers used)
    {
        var contract = registration.ContractValue;
        _ = writer.Append("() => new ").Append(registration.ConcreteTypeFullName).Append('(');

        var parameters = registration.ConstructorParameters;
        if (parameters.Length != 0)
        {
            _ = writer.OpenContinuation();
            for (var i = 0; i < parameters.Length; i++)
            {
                if (i != 0)
                {
                    _ = writer.ArgumentSeparator();
                }

                AppendParameter(writer, parameters[i], contract, ref used);
            }

            _ = writer.Outdent();
        }

        _ = writer.Append(')');

        var properties = registration.PropertyInjections;
        if (properties.Length == 0)
        {
            return;
        }

        _ = writer.EndLine().OpenBlock();
        for (var i = 0; i < properties.Length; i++)
        {
            var property = properties[i];
            _ = writer.Append(property.PropertyName).Append(" = ");
            AppendService(writer, property.TypeFullName, contract, ref used);
            _ = writer.ArgumentSeparator();
        }

        _ = writer.CloseBlockInline();
    }

    /// <summary>Writes the expression that resolves a constructor parameter.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="parameter">The parameter.</param>
    /// <param name="contract">The registration's contract, as C# source; <see langword="null"/> for none.</param>
    /// <param name="used">The throw helpers called so far, updated with the one this parameter calls.</param>
    /// <remarks>A collection resolves to every registration, which may be none, so it never throws.</remarks>
    internal static void AppendParameter(SourceWriter writer, in ConstructorParameter parameter, string? contract, ref ThrowHelpers used)
    {
        if (parameter.Kind != DependencyKind.Collection)
        {
            AppendService(writer, parameter.TypeFullName, contract, ref used);
            return;
        }

        _ = writer.Append("resolver.GetServices<").Append(parameter.InnerTypeFullName!).Append(">(");
        _ = contract is null ? writer.Append(')') : writer.Append(contract).Append(')');
    }

    /// <summary>Writes the expression that resolves one service, throwing when it is not registered.</summary>
    /// <param name="writer">The writer.</param>
    /// <param name="typeFullName">The fully qualified type of the service.</param>
    /// <param name="contract">The registration's contract, as C# source; <see langword="null"/> for none.</param>
    /// <param name="used">The throw helpers called so far, updated with the one this service calls.</param>
    internal static void AppendService(SourceWriter writer, string typeFullName, string? contract, ref ThrowHelpers used)
    {
        _ = writer.Append("resolver.GetService<").Append(typeFullName).Append(">(");
        if (contract is null)
        {
            used |= ThrowHelpers.WithoutContract;
            _ = writer.Append(") ?? ").Append(ThrowNotRegistered).Append('<').Append(typeFullName).Append(">(\"").Append(typeFullName).Append("\")");
            return;
        }

        used |= ThrowHelpers.WithContract;
        _ = writer.Append(contract).Append(") ?? ").Append(ThrowNotRegistered).Append('<').Append(typeFullName).Append(">(\"")
            .Append(typeFullName).Append("\", ").Append(contract).Append(')');
    }

    /// <summary>Writes the throw helpers the registrations call, after the registration method.</summary>
    /// <param name="writer">The writer, at the class body's level.</param>
    /// <param name="used">The helpers the registrations call.</param>
    internal static void AppendThrowHelpers(SourceWriter writer, ThrowHelpers used)
    {
        if ((used & ThrowHelpers.WithoutContract) != 0)
        {
            _ = writer.BlankLine().Lines(ThrowNotRegisteredMethod);
        }

        if ((used & ThrowHelpers.WithContract) != 0)
        {
            _ = writer.BlankLine().Lines(ThrowNotRegisteredWithContractMethod);
        }
    }

    /// <summary>Writes a trailing argument when there is one.</summary>
    /// <param name="writer">The writer, after the argument before it.</param>
    /// <param name="argument">The argument, as C# source; <see langword="null"/> for none.</param>
    /// <returns>The writer.</returns>
    private static SourceWriter AppendTrailingArgument(SourceWriter writer, string? argument) =>
        argument is null ? writer : writer.Append(", ").Append(argument);

    /// <summary>Separates a registration from the one before it with a blank line.</summary>
    /// <param name="writer">The writer, at the method body's level.</param>
    /// <param name="index">How many registrations have been written.</param>
    private static void SeparateRegistration(SourceWriter writer, int index)
    {
        if (index != 0)
        {
            _ = writer.BlankLine();
        }
    }
}
