//HintName: Splat.DI.Reg.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Splat
{
    /// <summary>
    /// Provides extension methods for the Splat dependency injection source generator.
    /// This partial class contains the generated implementation of dependency registrations.
    /// </summary>
    internal static partial class SplatRegistrations
    {
        /// <summary>
        /// Internal implementation of dependency injection setup.
        /// This method is generated at compile-time and contains all registrations
        /// defined through the source generator marker methods.
        /// </summary>
        /// <param name="resolver">The <see cref="Splat.IDependencyResolver"/> instance to register dependencies with.</param>
        static partial void SetupIOCInternal(Splat.IDependencyResolver resolver)
        {
            {
                global::System.Lazy<global::Test.ITest1> lazy = new global::System.Lazy<global::Test.ITest1>(() => new global::Test.TestConcrete1(resolver.GetService<global::Test.IService1>("Test1") ?? throw new global::System.InvalidOperationException("Dependency 'global::Test.IService1' with contract " + "Test1" + " not registered with Splat resolver."), resolver.GetService<global::Test.IService2>("Test1") ?? throw new global::System.InvalidOperationException("Dependency 'global::Test.IService2' with contract " + "Test1" + " not registered with Splat resolver.")));
                resolver.Register<global::System.Lazy<global::Test.ITest1>>(() => lazy, "Test1");
                resolver.Register<global::Test.ITest1>(() => lazy.Value, "Test1");
            }

            {
                global::System.Lazy<global::Test.ITest2> lazy = new global::System.Lazy<global::Test.ITest2>(() => new global::Test.TestConcrete2(resolver.GetService<global::Test.IService1>("Test1") ?? throw new global::System.InvalidOperationException("Dependency 'global::Test.IService1' with contract " + "Test1" + " not registered with Splat resolver."), resolver.GetService<global::Test.IService2>("Test1") ?? throw new global::System.InvalidOperationException("Dependency 'global::Test.IService2' with contract " + "Test1" + " not registered with Splat resolver.")));
                resolver.Register<global::System.Lazy<global::Test.ITest2>>(() => lazy, "Test1");
                resolver.Register<global::Test.ITest2>(() => lazy.Value, "Test1");
            }

            {
                global::System.Lazy<global::Test.ITest3> lazy = new global::System.Lazy<global::Test.ITest3>(() => new global::Test.TestConcrete3(resolver.GetService<global::Test.IService1>("Test1") ?? throw new global::System.InvalidOperationException("Dependency 'global::Test.IService1' with contract " + "Test1" + " not registered with Splat resolver."), resolver.GetService<global::Test.IService2>("Test1") ?? throw new global::System.InvalidOperationException("Dependency 'global::Test.IService2' with contract " + "Test1" + " not registered with Splat resolver.")));
                resolver.Register<global::System.Lazy<global::Test.ITest3>>(() => lazy, "Test1");
                resolver.Register<global::Test.ITest3>(() => lazy.Value, "Test1");
            }
        }
    }
}