//HintName: Splat.DI.Reg.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Splat
{
    /// <summary>
    /// Provides extension methods for the Splat dependency injection source generator.
    /// This partial class contains the generated implementation of dependency registrations.
    /// </summary>
    internal static partial class SplatRegistrations
    {
        /// <summary>
        /// Internal implementation of dependency injection setup.
        /// This method is generated at compile-time and contains all registrations
        /// defined through the source generator marker methods.
        /// </summary>
        /// <param name="resolver">The <see cref="Splat.IDependencyResolver"/> instance to register dependencies with.</param>
        static partial void SetupIOCInternal(Splat.IDependencyResolver resolver)
        {
            resolver.Register<global::Test.IAppUpdateService>(() => new global::Test.AppUpdateService<string>(resolver.GetService<global::Test.IConfig>("Test2") ?? throw new global::System.InvalidOperationException("Dependency 'global::Test.IConfig' with contract " + "Test2" + " not registered with Splat resolver.")), "Test2");
            resolver.Register<global::Test.IConfig>(() => new global::Test.Config(), "Test2");        }
    }
}