//HintName: Splat.DI.Reg.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Splat
{
    /// <summary>
    /// Provides extension methods for the Splat dependency injection source generator.
    /// This partial class contains the generated implementation of dependency registrations.
    /// </summary>
    internal static partial class SplatRegistrations
    {
        /// <summary>
        /// Internal implementation of dependency injection setup.
        /// This method is generated at compile-time and contains all registrations
        /// defined through the source generator marker methods.
        /// </summary>
        /// <param name="resolver">The <see cref="Splat.IDependencyResolver"/> instance to register dependencies with.</param>
        static partial void SetupIOCInternal(Splat.IDependencyResolver resolver)
        {
            resolver.Register<global::Test.ITest>(
                () => new global::Test.TestConcrete(
                    resolver.GetService<global::Test.IService1>("Test1") ?? ThrowNotRegistered<global::Test.IService1>("global::Test.IService1", "Test1"),
                    resolver.GetService<global::System.Lazy<global::Test.IService2>>("Test1") ?? ThrowNotRegistered<global::System.Lazy<global::Test.IService2>>("global::System.Lazy<global::Test.IService2>", "Test1"))
                {
                    ServiceProperty1 = resolver.GetService<global::Test.IServiceProperty1>("Test1") ?? ThrowNotRegistered<global::Test.IServiceProperty1>("global::Test.IServiceProperty1", "Test1"),
                    ServiceProperty2 = resolver.GetService<global::Test.IServiceProperty2>("Test1") ?? ThrowNotRegistered<global::Test.IServiceProperty2>("global::Test.IServiceProperty2", "Test1"),
                    ServiceProperty3 = resolver.GetService<global::Test.IServiceProperty3>("Test1") ?? ThrowNotRegistered<global::Test.IServiceProperty3>("global::Test.IServiceProperty3", "Test1"),
                },
                "Test1");

            resolver.Register<global::Test.IService1>(() => new global::Test.Service1(), "Test1");

            resolver.Register<global::Test.IService2>(() => new global::Test.Service2(), "Test1");
        }

        /// <summary>Throws for a dependency the resolver has no registration for under a contract.</summary>
        /// <typeparam name="T">The type of the dependency.</typeparam>
        /// <param name="typeName">The name of the dependency's type.</param>
        /// <param name="contract">The contract the dependency was asked for under.</param>
        /// <returns>Never returns.</returns>
        private static T ThrowNotRegistered<T>(string typeName, string contract)
        {
            throw new global::System.InvalidOperationException("Dependency '" + typeName + "' with contract " + contract + " not registered with Splat resolver.");
        }
    }
}
