//HintName: Splat.DI.Reg.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Splat
{
    /// <summary>
    /// Provides extension methods for the Splat dependency injection source generator.
    /// This partial class contains the generated implementation of dependency registrations.
    /// </summary>
    internal static partial class SplatRegistrations
    {
        /// <summary>
        /// Internal implementation of dependency injection setup.
        /// This method is generated at compile-time and contains all registrations
        /// defined through the source generator marker methods.
        /// </summary>
        /// <param name="resolver">The <see cref="Splat.IDependencyResolver"/> instance to register dependencies with.</param>
        static partial void SetupIOCInternal(Splat.IDependencyResolver resolver)
        {
            resolver.Register<global::Test.ITest>(
                () => new global::Test.TestConcrete(
                    resolver.GetService<global::System.Lazy<global::Test.Service1>>() ?? ThrowNotRegistered<global::System.Lazy<global::Test.Service1>>("global::System.Lazy<global::Test.Service1>")));
        }

        /// <summary>Throws for a dependency the resolver has no registration for.</summary>
        /// <typeparam name="T">The type of the dependency.</typeparam>
        /// <param name="typeName">The name of the dependency's type.</param>
        /// <returns>Never returns.</returns>
        private static T ThrowNotRegistered<T>(string typeName)
        {
            throw new global::System.InvalidOperationException("Dependency '" + typeName + "' not registered with Splat resolver.");
        }
    }
}
