//HintName: Splat.DI.Reg.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Splat
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Splat.DependencyInjection.SourceGenerator", "1.2.0.0")]
    internal static partial class SplatRegistrations
    {
        static partial void SetupIOCInternal(Splat.IDependencyResolver resolver)
        {
            {
                global::System.Lazy<global::Test.ITest1> lazy = new global::System.Lazy<global::Test.ITest1>(() => new global::Test.TestConcrete1(resolver.GetService<global::Test.ITest2>("Test2") ?? throw new global::System.InvalidOperationException("Dependency 'global::Test.ITest2' with contract " + "Test2" + " not registered with Splat resolver."), resolver.GetService<global::Test.IService2>("Test2") ?? throw new global::System.InvalidOperationException("Dependency 'global::Test.IService2' with contract " + "Test2" + " not registered with Splat resolver.")));
                resolver.Register<global::System.Lazy<global::Test.ITest1>>(() => lazy, "Test2");
                resolver.Register<global::Test.ITest1>(() => lazy.Value, "Test2");
            }
            {
                global::System.Lazy<global::Test.ITest2> lazy = new global::System.Lazy<global::Test.ITest2>(() => new global::Test.TestConcrete2(resolver.GetService<global::Test.ITest1>() ?? throw new global::System.InvalidOperationException("Dependency 'global::Test.ITest1' not registered with Splat resolver."), resolver.GetService<global::Test.IService2>() ?? throw new global::System.InvalidOperationException("Dependency 'global::Test.IService2' not registered with Splat resolver.")));
                resolver.Register<global::System.Lazy<global::Test.ITest2>>(() => lazy);
                resolver.Register<global::Test.ITest2>(() => lazy.Value);
            }        }
    }
}