//HintName: Splat.DI.Reg.g.cs
// <auto-generated />
namespace Splat
{
    internal static partial class SplatRegistrations
    {
        static partial void SetupIOCInternal(Splat.IDependencyResolver resolver)
        {
            {
                global::System.Lazy<global::Test.ITest> lazy = new global::System.Lazy<global::Test.ITest>(() => new global::Test.TestConcrete((global::Test.IService1)resolver.GetService(typeof(global::Test.IService1)), (global::Test.IService2)resolver.GetService(typeof(global::Test.IService2))), ExecutionAndPublication);
                resolver.Register<global::System.Lazy<global::Test.ITest>>(() => lazy, "Test2");
                resolver.Register<global::Test.ITest>(() => lazy.Value, "Test2");
            }
        }
    }
}
