//HintName: Splat.DI.Reg.g.cs
// <auto-generated />
namespace Splat
{
    internal static partial class SplatRegistrations
    {
        static partial void SetupIOCInternal(Splat.IDependencyResolver resolver)
        {
            {
                global::System.Lazy<global::Test.TestConcrete> lazy = new global::System.Lazy<global::Test.TestConcrete>(() => new global::Test.TestConcrete((global::Test.IService1)resolver.GetService(typeof(global::Test.IService1)), (global::Test.IService2)resolver.GetService(typeof(global::Test.IService2))));
                resolver.Register<global::System.Lazy<global::Test.TestConcrete>>(() => lazy, "Test2");
                resolver.Register<global::Test.TestConcrete>(() => lazy.Value, "Test2");
            }
        }
    }
}
