//HintName: Splat.DI.Reg.g.cs
// <auto-generated />
namespace Splat
{
    internal static partial class SplatRegistrations
    {
        static partial void SetupIOCInternal(Splat.IDependencyResolver resolver)
        {
            {
                global::System.Lazy<global::Test.ITest> lazy = new global::System.Lazy<global::Test.ITest>(() => new global::Test.TestConcrete());
                resolver.Register<global::System.Lazy<global::Test.ITest>>(() => lazy, "Test1");
                resolver.Register<global::Test.ITest>(() => lazy.Value, "Test1");
            }
        }
    }
}
