//HintName: Splat.DI.Reg.g.cs
// <auto-generated />
namespace Splat
{
    internal static partial class SplatRegistrations
    {
        static partial void SetupIOCInternal(Splat.IDependencyResolver resolver)
        {
            {
                global::System.Lazy<global::Test.ITest> lazy = new global::System.Lazy<global::Test.ITest>(() => new global::Test.TestConcrete1());
                resolver.Register<global::System.Lazy<global::Test.ITest>>(() => lazy);
                resolver.Register<global::Test.ITest>(() => lazy.Value);
            }
            {
                global::System.Lazy<global::Test.ITest> lazy = new global::System.Lazy<global::Test.ITest>(() => new global::Test.TestConcrete2());
                resolver.Register<global::System.Lazy<global::Test.ITest>>(() => lazy);
                resolver.Register<global::Test.ITest>(() => lazy.Value);
            }
        }
    }
}
