//HintName: Splat.DI.Reg.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Splat
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Splat.DependencyInjection.SourceGenerator", "1.2.0.0")]
    internal static partial class SplatRegistrations
    {
        static partial void SetupIOCInternal(Splat.IDependencyResolver resolver)
        {
            resolver.Register<global::Test.IService>(() => new global::Test.ServiceA(), "Test1");
            resolver.Register<global::Test.IService>(() => new global::Test.ServiceB(), "Test1");
            {
                global::System.Lazy<global::Test.ITest> lazy = new global::System.Lazy<global::Test.ITest>(() => new global::Test.TestConcrete(resolver.GetServices<global::Test.IService>("Test1")));
                resolver.Register<global::System.Lazy<global::Test.ITest>>(() => lazy, "Test1");
                resolver.Register<global::Test.ITest>(() => lazy.Value, "Test1");
            }
        }
    }
}
