//HintName: Splat.DI.Reg.g.cs
// <auto-generated />
namespace Splat
{
    internal static partial class SplatRegistrations
    {
        static partial void SetupIOCInternal(Splat.IDependencyResolver resolver)
        {
            resolver.Register<global::Test.ITest>(() => new global::Test.TestConcrete((global::Test.IService1)resolver.GetService(typeof(global::Test.IService1)), (global::System.Lazy<global::Test.IService2>)resolver.GetService(typeof(global::System.Lazy<global::Test.IService2>))), "Test1");
            resolver.Register<global::Test.IService1>(() => new global::Test.Service1(), "Test1");
            {
                global::System.Lazy<global::Test.IService2> lazy = new global::System.Lazy<global::Test.IService2>(() => new global::Test.Service2());
                resolver.Register<global::System.Lazy<global::Test.IService2>>(() => lazy, "Test1");
                resolver.Register<global::Test.IService2>(() => lazy.Value, "Test1");
            }
        }
    }
}
