//HintName: Splat.DI.Reg.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Splat
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Splat.DependencyInjection.SourceGenerator", "1.2.0.0")]
    internal static partial class SplatRegistrations
    {
        static partial void SetupIOCInternal(Splat.IDependencyResolver resolver)
        {
            resolver.Register<global::Test.ITest>(() => new global::Test.TestConcrete((global::Test.IService1)resolver.GetService(typeof(global::Test.IService1)), (global::System.Lazy<global::Test.IService2>)resolver.GetService(typeof(global::System.Lazy<global::Test.IService2>))), "Test2");
            resolver.Register<global::Test.IService1>(() => new global::Test.Service1(), "Test2");
            {
                global::System.Lazy<global::Test.IService2> lazy = new global::System.Lazy<global::Test.IService2>(() => new global::Test.Service2());
                resolver.Register<global::System.Lazy<global::Test.IService2>>(() => lazy, "Test2");
                resolver.Register<global::Test.IService2>(() => lazy.Value, "Test2");
            }
        }
    }
}
