//HintName: Splat.DI.Reg.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Splat
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Splat.DependencyInjection.SourceGenerator", "1.2.0.0")]
    internal static partial class SplatRegistrations
    {
        static partial void SetupIOCInternal(Splat.IDependencyResolver resolver)
        {
            {
                global::System.Lazy<global::Test.ITest1> lazy = new global::System.Lazy<global::Test.ITest1>(() => new global::Test.TestConcrete1((global::Test.IService1)resolver.GetService(typeof(global::Test.IService1)), (global::Test.IService2)resolver.GetService(typeof(global::Test.IService2))));
                resolver.Register<global::System.Lazy<global::Test.ITest1>>(() => lazy, "Test1");
                resolver.Register<global::Test.ITest1>(() => lazy.Value, "Test1");
            }
            {
                global::System.Lazy<global::Test.ITest2> lazy = new global::System.Lazy<global::Test.ITest2>(() => new global::Test.TestConcrete2((global::Test.IService1)resolver.GetService(typeof(global::Test.IService1)), (global::Test.IService2)resolver.GetService(typeof(global::Test.IService2))));
                resolver.Register<global::System.Lazy<global::Test.ITest2>>(() => lazy, "Test1");
                resolver.Register<global::Test.ITest2>(() => lazy.Value, "Test1");
            }
            {
                global::System.Lazy<global::Test.ITest3> lazy = new global::System.Lazy<global::Test.ITest3>(() => new global::Test.TestConcrete3((global::Test.IService1)resolver.GetService(typeof(global::Test.IService1)), (global::Test.IService2)resolver.GetService(typeof(global::Test.IService2))));
                resolver.Register<global::System.Lazy<global::Test.ITest3>>(() => lazy, "Test1");
                resolver.Register<global::Test.ITest3>(() => lazy.Value, "Test1");
            }
        }
    }
}
