//HintName: Splat.DI.Reg.g.cs
// <auto-generated />
namespace Splat
{
    internal static partial class SplatRegistrations
    {
        static partial void SetupIOCInternal(Splat.IDependencyResolver resolver)
        {
            resolver.Register<global::Test.ITest1>(() => new global::Test.TestConcrete1((global::Test.ITest2)resolver.GetService(typeof(global::Test.ITest2)), (global::Test.IService2)resolver.GetService(typeof(global::Test.IService2))));
            resolver.Register<global::Test.ITest2>(() => new global::Test.TestConcrete2((global::Test.ITest1)resolver.GetService(typeof(global::Test.ITest1)), (global::Test.IService2)resolver.GetService(typeof(global::Test.IService2))));
        }
    }
}
