//HintName: Splat.DI.Reg.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Splat
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Splat.DependencyInjection.SourceGenerator", "1.2.0.0")]
    internal static partial class SplatRegistrations
    {
        static partial void SetupIOCInternal(Splat.IDependencyResolver resolver)
        {
            resolver.Register<global::Test.ITest1>(() => new global::Test.TestConcrete1((global::Test.ITest2)resolver.GetService(typeof(global::Test.ITest2)), (global::Test.IService2)resolver.GetService(typeof(global::Test.IService2))));
            resolver.Register<global::Test.ITest2>(() => new global::Test.TestConcrete2((global::Test.ITest1)resolver.GetService(typeof(global::Test.ITest1)), (global::Test.IService2)resolver.GetService(typeof(global::Test.IService2))));
        }
    }
}
