//HintName: Splat.DI.Reg.g.cs
// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Splat
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Splat.DependencyInjection.SourceGenerator", "1.2.0.0")]
    internal static partial class SplatRegistrations
    {
        static partial void SetupIOCInternal(Splat.IDependencyResolver resolver)
        {
            resolver.Register<global::Test.ITest>(() => new global::Test.TestConcrete(resolver.GetService<global::Test.IService1>("Test2") ?? throw new global::System.InvalidOperationException("Dependency 'global::Test.IService1' with contract " + "Test2" + " not registered with Splat resolver."), resolver.GetService<global::System.Lazy<global::Test.IService2>>("Test2") ?? throw new global::System.InvalidOperationException("Dependency 'global::System.Lazy<global::Test.IService2>' with contract " + "Test2" + " not registered with Splat resolver.")) { ServiceProperty1 = resolver.GetService<global::Test.IServiceProperty1>("Test2") ?? throw new global::System.InvalidOperationException("Dependency 'global::Test.IServiceProperty1' with contract " + "Test2" + " not registered with Splat resolver."), ServiceProperty2 = resolver.GetService<global::Test.IServiceProperty2>("Test2") ?? throw new global::System.InvalidOperationException("Dependency 'global::Test.IServiceProperty2' with contract " + "Test2" + " not registered with Splat resolver."), ServiceProperty3 = resolver.GetService<global::Test.IServiceProperty3>("Test2") ?? throw new global::System.InvalidOperationException("Dependency 'global::Test.IServiceProperty3' with contract " + "Test2" + " not registered with Splat resolver.") }, "Test2");
            resolver.Register<global::Test.IService1>(() => new global::Test.Service1(), "Test2");
            resolver.Register<global::Test.IService2>(() => new global::Test.Service2(), "Test2");
        }
    }
}
