//HintName: Splat.DI.Reg.g.cs
// <auto-generated />
namespace Splat
{
    internal static partial class SplatRegistrations
    {
        static partial void SetupIOCInternal(Splat.IDependencyResolver resolver)
        {
            resolver.Register<global::Test.ITest>(() => new global::Test.TestConcrete((global::System.Lazy<global::Test.Service1>)resolver.GetService(typeof(global::System.Lazy<global::Test.Service1>))), "Test2");
        }
    }
}
