//HintName: Microsoft.CodeAnalysis.EmbeddedAttribute.g.cs

// <auto-generated />
namespace Microsoft.CodeAnalysis
{
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct | System.AttributeTargets.Enum | System.AttributeTargets.Interface | System.AttributeTargets.Delegate, AllowMultiple = false, Inherited = false)]
    [System.Diagnostics.Conditional("NEVER_DEFINED")]
    internal sealed class EmbeddedAttribute : System.Attribute
    {
    }
}