name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  productNamespacePrefix: "Splat.DependencyInjection"

# Needed so the reusable workflow can optionally delete the temp per-OS artifacts it creates.
permissions:
  contents: read
  actions: write

jobs:
  build:
    uses: reactiveui/actions-common/.github/workflows/workflow-common-setup-and-build.yml@b285525c4af878b0fe3fbb00d9f2ae862e402395 # main
    with:
      productNamespacePrefix: Splat.DependencyInjection
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
